name: 构建 Tauri 桌面版本
on:
  - push
  - workflow_dispatch

permissions:
  contents: write

jobs:
  clean-pre-release:
    name: 删除预发布版本的构建产物
    runs-on: ubuntu-latest
    steps:
      - name: 删除预发布版本的构建产物
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          assets: |
            *.*
          tag: ${{ github.ref_name }}-release
          fail-if-no-assets: false
          fail-if-no-release: false
  build-tauri-desktop:
    name: 构建 Tauri 桌面版本
    needs: clean-pre-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            args: ""
            name: linux
            arch: x86_64
          - platform: windows-latest
            args: ""
            name: windows
            arch: x86_64
          - platform: macos-latest # arm64 二进制包
            args: "--target aarch64-apple-darwin"
            name: macOS
            arch: aarch64
          - platform: macos-latest # x86 二进制包
            args: "--target x86_64-apple-darwin"
            name: macOS
            arch: x86_64
          - platform: macos-latest # 通用二进制包
            args: "--target universal-apple-darwin"
            name: macOS
            arch: universal

    runs-on: ${{ matrix.platform }}
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 缓存 Rust 依赖
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./src-tauri -> target

      - name: 安装 PNPM
        uses: pnpm/action-setup@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: 安装 wasm32 目标
        run: rustup target add wasm32-unknown-unknown

      # macOS 自带的 Xcode LLVM 不支持 WASM 目标
      - name: "macOS: 安装 LLVM 和 Clang"
        uses: KyleMayes/install-llvm-action@v2
        if: matrix.platform == 'macos-latest'
        with:
          version: "15"

      - name: 安装 Tauri 所需系统依赖（仅 Linux）
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libappindicator3-dev libwebkit2gtk-4.1-dev librsvg2-dev patchelf

      - name: 安装前端依赖
        run: pnpm i

      - name: 更新版本号
        run: node scripts/update-version.ts

      - name: 构建 AMLL TTML Tools 程序并发布自动构建
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: ${{ github.ref_name }}-release
          includeUpdaterJson: true
          releaseName: AMLL TTML Tools ${{ github.ref_name }} branch build
          releaseBody: |
            Latest ${{ github.ref_name }} branch development build.
            最新 ${{ github.ref_name }} 分支构建。
          args: ${{ matrix.args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: 上传产物到 Action Artifact
        uses: actions/upload-artifact@v6
        with:
          name: AMLL TTML Tools ${{matrix.name}}-${{matrix.arch}}
          path: |
            src-tauri/target/**/release/bundle/**/*
            src-tauri/target/**/release/amll-ttml-tool.exe
            src-tauri/target/**/release/amll-ttml-tool
